name: projeto1
description: Meu primeiro app Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Pacotes que vocÃª disse que quer de volta
  google_fonts: ^6.3.2
  http: ^1.6.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  ffi: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/logo.jpeg
